version: '3.7'

services:
  worker:
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: '2GB'
    env_file:
      - .env
    restart: always
    volumes:
      - ./temp:/app/temp
      - ./src:/app/src
    build:
      context: .
      dockerfile: './docker/dockerfile.${DOCKERFILE}'

networks:
  services:
    name: okami_services
